# Generated by Django 3.1.3 on 2020-11-25 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0017_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skin_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_score', models.IntegerField(default=0)),
                ('to_score', models.IntegerField(default=0)),
                ('skin_status', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.category')),
            ],
        ),
    ]
