# Generated by Django 3.1.3 on 2020-11-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0018_skin_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin_profile',
            name='from_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='skin_profile',
            name='to_score',
            field=models.FloatField(default=0),
        ),
    ]
