# Generated by Django 3.1.3 on 2020-11-25 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0020_skintest'),
    ]

    operations = [
        migrations.AddField(
            model_name='concerns',
            name='skin_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizapp.skintest'),
        ),
        migrations.AddField(
            model_name='hydration',
            name='skin_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizapp.skintest'),
        ),
        migrations.AddField(
            model_name='quizmodal',
            name='skin_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizapp.skintest'),
        ),
    ]
