# Generated by Django 3.1.3 on 2020-11-27 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0023_auto_20201126_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skintest',
            name='personalcare',
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizapp.question'),
        ),
    ]
