# Generated by Django 3.1.3 on 2020-12-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0024_auto_20201127_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skintest',
            name='code',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
