# Generated by Django 3.1.3 on 2020-12-07 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0025_auto_20201205_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skintest',
            name='customer',
        ),
    ]
